### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Sycration** [ld-cd/AssociationFireAccountability-Client#6]
There is no included license with this project or with the api. Add one. The MIT is good for APIs. Create one if it is proprietary.

**Comment by jaren** [comment]
How did you even find this?

**Comment by glen3b** [comment]
Related issue, in the sense that both intend to improve ability of other developers to use these projects: VectorBlog/FireAlarmWidget#3.

**Comment by ld-cd** [comment]
I've GPL'd this code, but it's crap, and if you ever plan on using something like it I would recommend you rewrite it from scratch.

Most of the infrastructure has been held together by duct tape for the past 3 odd years, and unfortunately I do not have the time to document it. If you'd like to use other components of this project is recommend you ask their respective authors to grant you some kind of license, they'd be perfectly happy to provide some help time permitting if you'd tell us your plans. All of us are currently extremely busy and we left high school behind quite a while ago, so we don't have any plans of maintaining anything beyond the simplest fixes (there are several outstanding issues in the code base at the moment).

If you'd like to build a compatible backend for this code, you can probably find an (outdated) spec of the API for this project if you look back through my gists that you may feel free to implement and modify as you please.

If you're curious about how to build the monitor it consists of a pi, an MCP3008 adc attached over spi, and an amplified electret mike. Unfortunately there exist no schematics for this because I built it while watching a subtitled German TV show, but it's pretty simple.
